spring.application.name=ORDER-SERVICE
server.port=8082

user.service.url=http://localhost:8081
payment.service.url=http://localhost:8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

resilience4j.retry.instances.paymentRetry.max-attempts=3
resilience4j.retry.instances.paymentRetry.wait-duration=500ms

resilience4j.circuitbreaker.instances.paymentCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.paymentCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.paymentCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.paymentCB.minimum-number-of-calls=2

spring.config.import=optional:configserver:http://localhost:8888
spring.profiles.active=dev

logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.circuitbreaker=DEBUG
logging.level.io.github.resilience4j=DEBUG

resilience4j.retry.instances.userRetry.max-attempts=3
resilience4j.retry.instances.userRetry.wait-duration=500ms
#resilience4j.retry.instances.userRetry.retry-exceptions=com.microservice.order.exception.UserServiceUnavailableException

resilience4j.circuitbreaker.instances.userCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.userCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userCB.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userCB.minimum-number-of-calls=2

spring.security.user.name=Abhi
spring.security.user.password=abhi8344

spring.datasource.url=jdbc:mysql://localhost:3306/orderdb
spring.datasource.username=root
spring.datasource.password=GR24@abhi

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true